<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CommuneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("communes")->insert(["description" => "Arica",	"id_reg" => 15]);
        DB::table("communes")->insert(["description" => "Camarones",	"id_reg" => 15]);
        DB::table("communes")->insert(["description" => "Putre",	"id_reg" => 15]);
        DB::table("communes")->insert(["description" => "General Lagos",	"id_reg" => 15]);
        DB::table("communes")->insert(["description" => "Iquique",	"id_reg" => 1]);
        DB::table("communes")->insert(["description" => "Camiña",	"id_reg" => 1]);
        DB::table("communes")->insert(["description" => "Colchane",	"id_reg" => 1]);
        DB::table("communes")->insert(["description" => "Huara",	"id_reg" => 1]);
        DB::table("communes")->insert(["description" => "Pica",	"id_reg" => 1]);
        DB::table("communes")->insert(["description" => "Pozo Almonte",	"id_reg" => 1]);
        DB::table("communes")->insert(["description" => "Alto Hospicio",	"id_reg" => 1]);
        DB::table("communes")->insert(["description" => "Antofagasta",	"id_reg" => 2]);
        DB::table("communes")->insert(["description" => "Mejillones",	"id_reg" => 2]);
        DB::table("communes")->insert(["description" => "Sierra Gorda",	"id_reg" => 2]);
        DB::table("communes")->insert(["description" => "Taltal",	"id_reg" => 2]);
        DB::table("communes")->insert(["description" => "Calama",	"id_reg" => 2]);
        DB::table("communes")->insert(["description" => "Ollagüe",	"id_reg" => 2]);
        DB::table("communes")->insert(["description" => "San Pedro 3",	"id_reg" => 2]);
        DB::table("communes")->insert(["description" => "Tocopilla",	"id_reg" => 2]);
        DB::table("communes")->insert(["description" => "María Elena",	"id_reg" => 2]);
        DB::table("communes")->insert(["description" => "Copiapó",	"id_reg" => 3]);
        DB::table("communes")->insert(["description" => "Caldera",	"id_reg" => 3]);
        DB::table("communes")->insert(["description" => "Tierra Amarilla",	"id_reg" => 3]);
        DB::table("communes")->insert(["description" => "Chañaral",	"id_reg" => 3]);
        DB::table("communes")->insert(["description" => "Diego de Almagro",	"id_reg" => 3]);
        DB::table("communes")->insert(["description" => "Vallenar",	"id_reg" => 3]);
        DB::table("communes")->insert(["description" => "Alto del Carmen",	"id_reg" => 3]);
        DB::table("communes")->insert(["description" => "Freirina",	"id_reg" => 3]);
        DB::table("communes")->insert(["description" => "Huasco",	"id_reg" => 3]);
        DB::table("communes")->insert(["description" => "La Serena",	"id_reg" => 4]);
        DB::table("communes")->insert(["description" => "Coquimbo",	"id_reg" => 4]);
        DB::table("communes")->insert(["description" => "Andacollo",	"id_reg" => 4]);
        DB::table("communes")->insert(["description" => "La Higuera",	"id_reg" => 4]);
        DB::table("communes")->insert(["description" => "Paiguano",	"id_reg" => 4]);
        DB::table("communes")->insert(["description" => "Vicuña",	"id_reg" => 4]);
        DB::table("communes")->insert(["description" => "Illapel",	"id_reg" => 4]);
        DB::table("communes")->insert(["description" => "Canela",	"id_reg" => 4]);
        DB::table("communes")->insert(["description" => "Los Vilos",	"id_reg" => 4]);
        DB::table("communes")->insert(["description" => "Salamanca",	"id_reg" => 4]);
        DB::table("communes")->insert(["description" => "Ovalle",	"id_reg" => 4]);
        DB::table("communes")->insert(["description" => "Combarbalá",	"id_reg" => 4]);
        DB::table("communes")->insert(["description" => "Monte Patria",	"id_reg" => 4]);
        DB::table("communes")->insert(["description" => "Punitaqui",	"id_reg" => 4]);
        DB::table("communes")->insert(["description" => "Río Hurtado",	"id_reg" => 4]);
        DB::table("communes")->insert(["description" => "Valparaíso",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Casablanca",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Concón",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Juan Fernández",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Puchuncaví",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Quilpué",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Quintero",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Villa Alemana",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Viña del Mar",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Isla  de Pascua",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Los Andes",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Calle Larga",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Rinconada",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "San Esteban",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "La Ligua",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Cabildo",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Papudo",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Petorca",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Zapallar",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Quillota",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Calera",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Hijuelas",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "La Cruz",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Limache",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Nogales",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Olmué",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "San Antonio",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Algarrobo",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Cartagena",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "El Quisco",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "El Tabo",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Santo Domingo",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "San Felipe",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Catemu",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Llaillay",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Panquehue",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Putaendo",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Santa María",	"id_reg" => 5]);
        DB::table("communes")->insert(["description" => "Rancagua",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Codegua",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Coinco",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Coltauco",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Doñihue",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Graneros",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Las Cabras",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Machalí",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Malloa",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Mostazal",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Olivar",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Peumo",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Pichidegua",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Quinta de Tilcoco",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Rengo",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Requínoa",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "San Vicente",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Pichilemu",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "La Estrella",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Litueche",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Marchihue",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Navidad",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Paredones",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "San Fernando",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Chépica",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Chimbarongo",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Lolol",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Nancagua",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Palmilla",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Peralillo",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Placilla",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Pumanque",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Santa Cruz",	"id_reg" => 6]);
        DB::table("communes")->insert(["description" => "Talca",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Constitución",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Curepto",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Empedrado",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Maule",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Pelarco",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Pencahue",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Río Claro",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "San Clemente",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "San Rafael",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Cauquenes",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Chanco",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Pelluhue",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Curicó",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Hualañé",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Licantén",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Molina",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Rauco",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Romeral",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Sagrada Familia",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Teno",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Vichuquén",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Linares",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Colbún",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Longaví",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Parral",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Retiro",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "San Javier",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Villa Alegre",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Yerbas Buenas",	"id_reg" => 7]);
        DB::table("communes")->insert(["description" => "Concepción",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Coronel",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Chiguayante",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Florida",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Hualqui",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Lota",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Penco",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "San Pedro de la Paz",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Santa Juana",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Talcahuano",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Tomé",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Hualpén",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Lebu",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Arauco",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Cañete",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Contulmo",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Curanilahue",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Los Álamos",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Tirúa",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Los Ángeles",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Antuco",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Cabrero",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Laja",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Mulchén",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Nacimiento",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Negrete",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Quilaco",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Quilleco",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "San Rosendo",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Santa Bárbara",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Tucapel",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Yumbel",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Alto Biobío",	"id_reg" => 8]);
        DB::table("communes")->insert(["description" => "Chillán",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "Bulnes",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "Cobquecura",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "Coelemu",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "Coihueco",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "Chillán Viejo",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "El Carmen",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "Ninhue",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "Ñiquén",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "Pemuco",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "Pinto",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "Portezuelo",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "Quillón",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "Quirihue",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "Ránquil",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "San Carlos",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "San Fabián",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "San Ignacio",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "San Nicolás",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "Treguaco",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "Yungay",	"id_reg" => 16]);
        DB::table("communes")->insert(["description" => "Temuco",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Carahue",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Cunco",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Curarrehue",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Freire",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Galvarino",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Gorbea",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Lautaro",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Loncoche",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Melipeuco",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Nueva Imperial",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Padre Las Casas",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Perquenco",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Pitrufquén",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Pucón",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Saavedra",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Teodoro Schmidt",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Toltén",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Vilcún",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Villarrica",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Cholchol",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Angol",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Collipulli",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Curacautín",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Ercilla",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Lonquimay",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Los Sauces",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Lumaco",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Purén",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Renaico",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Traiguén",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Victoria",	"id_reg" => 9]);
        DB::table("communes")->insert(["description" => "Valdivia",	"id_reg" => 14]);
        DB::table("communes")->insert(["description" => "Corral",	"id_reg" => 14]);
        DB::table("communes")->insert(["description" => "Futrono",	"id_reg" => 14]);
        DB::table("communes")->insert(["description" => "La Unión",	"id_reg" => 14]);
        DB::table("communes")->insert(["description" => "Lago Ranco",	"id_reg" => 14]);
        DB::table("communes")->insert(["description" => "Lanco",	"id_reg" => 14]);
        DB::table("communes")->insert(["description" => "Los Lagos",	"id_reg" => 14]);
        DB::table("communes")->insert(["description" => "Máfil",	"id_reg" => 14]);
        DB::table("communes")->insert(["description" => "Mariquina",	"id_reg" => 14]);
        DB::table("communes")->insert(["description" => "Paillaco",	"id_reg" => 14]);
        DB::table("communes")->insert(["description" => "Panguipulli",	"id_reg" => 14]);
        DB::table("communes")->insert(["description" => "Río Bueno",	"id_reg" => 14]);
        DB::table("communes")->insert(["description" => "Puerto Montt",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Calbuco",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Cochamó",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Fresia",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Frutillar",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Los Muermos",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Llanquihue",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Maullín",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Puerto Varas",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Castro",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Ancud",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Chonchi",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Curaco de Vélez",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Dalcahue",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Puqueldón",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Queilén",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Quellón",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Quemchi",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Quinchao",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Osorno",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Puerto Octay",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Purranque",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Puyehue",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Río Negro",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "San Juan de la Costa",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "San Pablo",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Chaitén",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Futaleufú",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Hualaihué",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Palena",	"id_reg" => 10]);
        DB::table("communes")->insert(["description" => "Coihaique",	"id_reg" => 11]);
        DB::table("communes")->insert(["description" => "Lago Verde",	"id_reg" => 11]);
        DB::table("communes")->insert(["description" => "Aisén",	"id_reg" => 11]);
        DB::table("communes")->insert(["description" => "Cisnes",	"id_reg" => 11]);
        DB::table("communes")->insert(["description" => "Guaitecas",	"id_reg" => 11]);
        DB::table("communes")->insert(["description" => "Cochrane",	"id_reg" => 11]);
        DB::table("communes")->insert(["description" => "O'Higgins",	"id_reg" => 11]);
        DB::table("communes")->insert(["description" => "Tortel",	"id_reg" => 11]);
        DB::table("communes")->insert(["description" => "Chile Chico",	"id_reg" => 11]);
        DB::table("communes")->insert(["description" => "Río Ibáñez",	"id_reg" => 11]);
        DB::table("communes")->insert(["description" => "Punta Arenas",	"id_reg" => 12]);
        DB::table("communes")->insert(["description" => "Laguna Blanca",	"id_reg" => 12]);
        DB::table("communes")->insert(["description" => "Río Verde",	"id_reg" => 12]);
        DB::table("communes")->insert(["description" => "San Gregorio",	"id_reg" => 12]);
        DB::table("communes")->insert(["description" => "Cabo de Hornos",	"id_reg" => 12]);
        DB::table("communes")->insert(["description" => "Antártica",	"id_reg" => 12]);
        DB::table("communes")->insert(["description" => "Porvenir",	"id_reg" => 12]);
        DB::table("communes")->insert(["description" => "Primavera",	"id_reg" => 12]);
        DB::table("communes")->insert(["description" => "Timaukel",	"id_reg" => 12]);
        DB::table("communes")->insert(["description" => "Natales",	"id_reg" => 12]);
        DB::table("communes")->insert(["description" => "Torres del Paine",	"id_reg" => 12]);
        DB::table("communes")->insert(["description" => "Santiago",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Cerrillos",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Cerro Navia",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Conchalí",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "El Bosque",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Estación Central",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Huechuraba",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Independencia",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "La Cisterna",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "La Florida",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "La Granja",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "La Pintana",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "La Reina",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Las Condes",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Lo Barnechea",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Lo Espejo",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Lo Prado",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Macul",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Maipú",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Ñuñoa",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Pedro Aguirre Cerda",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Peñalolén",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Providencia",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Pudahuel",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Quilicura",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Quinta Normal",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Recoleta",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Renca",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "San Joaquín",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "San Miguel",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "San Ramón",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Vitacura",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Puente Alto",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Pirque",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "San José de Maipo",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Colina",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Lampa",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Tiltil",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "San Bernardo",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Buin",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Calera de Tango",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Paine",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Melipilla",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Alhué",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Curacaví",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "María Pinto",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "San Pedro",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Talagante",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "El Monte",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Isla de Maipo",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Padre Hurtado",	"id_reg" => 13]);
        DB::table("communes")->insert(["description" => "Peñaflor",	"id_reg" => 13]);

    }
}
